/**
 * @description This page contains custom styling for MUI Components
 * The styling of MUI Components
 * @author Sanjana Rao
 * @since 11-02-2022
 */
import { makeStyles } from '@material-ui/core';

const useStyle = makeStyles(() => ({
  container: {
    backgroundColor: '#fff',
  },
  productContainer: {
    width: '41.66%',
    bottom: '0',
    backgroundColor: 'rgb(255, 255, 255)',
    padding: '16px',
  },
  image: {
    transition: 'opacity .5s linear',
    opacity: 1,
    borderRadius: '2px',
    maxWidth: '100%',
    maxHeight: '100%',
  },
  productImage: {
    float: 'left',
    position: 'relative',
  },
  CartButtons: {
    marginTop: '35px',
    display: 'flex',
    justifyContent: 'space-between',
  },
  button: {
    width: '60%',
    height: 50,
  },
  productDetails: {
    padding: '0px 0px 0px 44px',
  },
  title: {
    marginTop: '12px',
    color: '#535665',
    display: 'block',
    fontWeight: 400,
    fontSize: '20px',
    lineHeight: '1',
    padding: '5px 20px 14px 0',
    opacity: '0.8',
  },
  desc: {
    color: '#212121',
  },
  tagline: {
    color: '#26a541',
    margin: '6px 0 -4px',
  },
  priceContainer: {
    display: 'inline-flex',
  },
  sp: {
    fontSize: '24px',
    verticalAlign: 'sub',
    fontWeight: 550,
    color: '#282c3f',
  },
  op: {
    fontSize: '20px',
    marginLeft: '12px',
    verticalAlign: 'middle',
    color: '#878787',
    textDecoration: 'line-through',
    alignSelf: 'center',
    lineHeight: '1.2',
  },
  discount: {
    marginLeft: '12px',
    fontSize: '20px',
    fontWeight: '550',
    color: '#ff905a',
    lineHeight: '1',
    verticalAlign: 'middle',
    alignSelf: 'center',
    letterSpacing: '0.5px',
  },
  alert: {
    display: 'inline',
    marginLeft: '12px',
    fontWeight: '500',
    color: '#ff6161',
    alignSelf: 'center',
  },
  ratingContainer: {
    marginBottom: '6px',
    cursor: 'pointer',
    zIndex: '1',
    position: 'absolute',
    marginLeft: '10px',
    fontSize: '20px',
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '1px',
    border: '1px solid #d4d5d9',
    padding: '1px 3px 3px 4px',
    backgroundColor: 'hsla(0,0%,100%,.8)',
    width: 'auto',
    borderBottom: '1px solid #d4d5d9',
    '&:hover': {
      border: '1px solid black',
    },
  },
  ratings: {
    fontSize: '16px',
    fontWeight: '600',
    display: 'inline-block',
    fontFamily: 'Whitney,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif',
  },
  raters: {
    display: 'inline-block',
    fontSize: '16px',
    color: '#535665',
    fontFamily: 'Whitney,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif',
  },
  star: {
    paddingLeft: '0.3em',
    color: '#17684F',
    display: 'inline-block',
    marginRight: '3px',
  },
  smallText: {
    color: '#03a685',
    fontWeight: 500,
    fontSize: '13px',
    display: 'block',
    margin: '0 10px 0 0',
  },
  sizing: {
    display: 'inline-block',
    paddingTop: '20px',
    fontSize: '15px',
    margin: '0',
    fontWeight: 500,
  },
  selectSize: {
    outline: 0,
    backgroundColor: 'transparent',
    border: 0,
    letterSpacing: '0.5px',
    textAlign: 'right',
    padding: '0 0 5px',
    color: '#ff3e6c',
    fontSize: '14px',
    fontWeight: 500,
    textTransform: 'uppercase',
    marginLeft: '40px',
  },
  sizes: {
    backgroundColor: '#fff',
    border: '1px solid #bfc0c6',
    borderRadius: '50px',
    minWidth: '50px',
    height: '50px',
    textAlign: 'center',
    cursor: 'pointer',
    color: '#282c3f',
    padding: '10px 10px 10px 10px',
    fontWeight: 600,
    fontSize: '14px',
    '&:hover': {
      border: '1px solid #ff3e6c',
      color: '#ff3e6c',
    },
    '&:active': {
      border: '1px solid #ff3e6c',
      color: '#ff3e6c',
    },
  },
  wishlist: {
    fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid #d4d5d9',
    background: '#fff',
    letterSpacing: '.4px',
    color: '#282c3f',
    fontSize: '16px',
    width: '60%',
    height: 50,
  },
  deliveryOp: {
    paddingTop: '40px',
    display: 'inline-block',
  },
  delivery: {
    fontWeight: 750,
    display: 'inline-block',
    fontSize: '16px',
    margin: '0',
    textTransform: 'uppercase',
    color: '#282c3f',
    fontFamily: 'Whitney,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif',
    marginRight: '10px',
  },
  img: {
    display: 'inline-block',
    position: 'absolute',
  },
  deliveryDetails: {
    paddingTop: '15px',
  },
  deliveryText: {
    color: '#282c3f',
    fontSize: '16px',
    fontFamily: 'Whitney,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif',
    margin: '5px 15px',
    display: 'inline-block',
    width: '90%',
    verticalAlign: 'top',
  },
  bestOfferText: {
    color: '#282c3f',
    fontSize: '16px',
    fontFamily: 'Whitney,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif',
    margin: '5px 15px',
    display: 'inline-block',
    verticalAlign: 'top',
  },
  descDetails: {
    textTransform: 'capitalize',
    fontWeight: 600,
    fontSize: '16px',
    border: 'none',
    paddingBottom: '5px',
    color: '#282c3f',
  },
  selectCheck: {
    outline: 0,
    backgroundColor: 'transparent',
    border: 0,
    letterSpacing: '0.5px',
    textAlign: 'right',
    padding: '0 0 5px',
    color: '#878787',
    fontSize: '14px',
    fontWeight: 500,
    textTransform: 'uppercase',
    marginLeft: '10px',
    marginTop: '10px',
    paddingTop: '20px',
  },
  selectedSizes: {
    border: '1px solid #ff3f6c',
    backgroundColor: '#fff',
    color: '#ff3f6c',
  },
}));
export default useStyle;
