/**
 * Data for action types
 * @author Sanjana Rao
 */
const actionTypes = {
  SET_LOGIN: 'SET_LOGIN',
  SET_TOP_BRANDS: 'SET_TOP_BRANDS',
  SET_BIG_TOP_BRANDS: 'SET_BIG_TOP_BRANDS',
  SET_CATEGORIES_TO_BAG: 'SET_CATEGORIES_TO_BAG',
  SET_LUXE: 'SET_LUXE',
  SET_INDIAN_WEAR: 'SET_INDIAN_WEAR',
  SET_SPORTS_WEAR: 'SET_SPORTS_WEAR',
  SET_FOOTWEAR: 'SET_FOOTWEAR',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_CATEGORY: 'SET_CATEGORY',
  SET_ONE_PRODUCT: 'SET_ONE_PRODUCT',
  SET_CART: 'SET_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_CART: 'UPDATE_CART',
  DELETE_CART: 'DELETE_CART',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_EMPTY_CART: 'SET_EMPTY_CART',
};
export default actionTypes;
